package com.telus.argus

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Validates FNV-1a hash parity with the JavaScript reference implementation
 * in functions/index.js.
 *
 * Test vectors were generated by running the JS fnv1aHash function directly.
 */
class FNV1aTest {

    @Test
    fun `hash produces correct value for empty string`() {
        // FNV offset basis
        assertEquals(0x811c9dc5u, FNV1a.hash(""))
    }

    @Test
    fun `hash matches JS reference for simple input`() {
        // JS: fnv1aHash("test") === 2949673445
        assertEquals(2949673445u, FNV1a.hash("test"))
    }

    @Test
    fun `hash matches JS reference for rollout input`() {
        // JS: fnv1aHash("test-seed-abcuser-123") === 4113345326
        assertEquals(4113345326u, FNV1a.hash("test-seed-abcuser-123"))
    }

    @Test
    fun `hash matches JS reference for hello`() {
        // JS: fnv1aHash("hello") === 1335831723
        assertEquals(1335831723u, FNV1a.hash("hello"))
    }

    @Test
    fun `hash matches JS reference for foobar`() {
        // JS: fnv1aHash("foobar") === 3214735720
        assertEquals(3214735720u, FNV1a.hash("foobar"))
    }

    @Test
    fun `percentageBucket returns value in 0-99 range`() {
        val bucket = FNV1a.percentageBucket("seed", "user-1")
        assertTrue("Bucket $bucket should be in 0..99", bucket in 0..99)
    }

    @Test
    fun `percentageBucket matches JS reference`() {
        // JS: percentageBucket("seed", "user-1") === 57
        assertEquals(57, FNV1a.percentageBucket("seed", "user-1"))
    }

    @Test
    fun `percentageBucket is deterministic`() {
        val a = FNV1a.percentageBucket("seed", "user-1")
        val b = FNV1a.percentageBucket("seed", "user-1")
        assertEquals(a, b)
    }

    @Test
    fun `percentageBucket differs for different users`() {
        val buckets = (1..100).map {
            FNV1a.percentageBucket("seed", "user-$it")
        }.toSet()
        // With 100 users, we expect meaningful distribution
        assertTrue("Expected more than 1 unique bucket, got ${buckets.size}", buckets.size > 1)
    }

    @Test
    fun `hash handles single character`() {
        // FNV-1a of "a": offset_basis XOR 97 then multiply by prime
        val expected = (0x811c9dc5u xor 97u) * 0x01000193u
        assertEquals(expected, FNV1a.hash("a"))
    }
}
